import {catalog} from './catalog.js';
const instructions={push:'按下按钮，再松开。',ripple:'点击按钮，涟漪从点击位置扩散。',wipe:'悬停或点击按钮，让色块擦过。',roll:'悬停或点击，字母依次翻滚。',hold:'按住按钮或回车键，直到充能完成。',burst:'点击按钮，观察闪光、冲击波与碎片。',glitch:'悬停或点击，体验信号错位。',jelly:'点击按钮，观察挤压与回弹。',shake:'点击按钮，观察错误反馈。',tilt:'移动鼠标或点击，卡片朝你倾斜。',toggle:'点击或按空格切换开关。',submit:'点击提交，观察加载与成功。',magnetic:'移动鼠标或点击舞台，按钮会追过来。',trail:'划过鼠标或按回车，图片沿轨迹留下来。',spotlight:'移动鼠标、点击或按回车，照亮隐藏海报。',custom:'移动鼠标或点击，反色光标跟随移动。',ink:'移动鼠标或点击，墨迹沿轨迹移动。',split:'调整文字与间隔，在工具中重播逐字进场。',scramble:'调整文字与时长，在工具中重播乱码解码。',wave:'点击或在工具中播放，观察字重波浪。',mask:'点击或在工具中播放，文字从轮廓填满。',typewriter:'点击或在工具中播放，文字逐字出现。',parallax:'向下滚动，远近图层移动的距离不同。',pinned:'继续向下滚动，画面钉住，章节依次变化。',horizontal:'向下滚动，长卷向左移动。',reveal:'向下滚动，遮罩逐渐揭开。',velocity:'滚动越快，画面倾斜越明显。',flip:'点击重排按钮，卡片平滑移动到新位置。',shared:'点击小图打开详情，再关闭详情。',curtain:'点击或在工具中播放，幕布盖住再揭开画面。',native:'点击切换场景，不支持原生转场时使用淡入淡出。',distortion:'移动鼠标或点击图片，让它像水面一样扭曲。',dissolve:'点击图片，在两张照片之间溶解切换。',gradient:'点击渐变，切换流动方向。',particles:'点击或碰到粒子，让它们散开再聚合。',easing:'拖动控制点或用方向键调整曲线；可直接输入坐标。',spring:'点击释放卡片，调整刚度与阻尼比较回弹。',duration:'点击任意一行，比较三种时长。',stagger:'调整间隔与方向，在工具中一起播放。',inertia:'拖住卡片甩出去；键盘可用方向键和回车。',rubber:'拖过虚线边界再松手；键盘可用方向键和回车。',swipe:'快速左右甩走卡片，慢慢松手会归位；支持方向键。',pull:'从列表向下拉，超过刻度后松手刷新；支持方向键和回车。'};
for(const entry of catalog){const root=document.querySelector(`.card[data-k="${entry.key}"]`),stage=root.querySelector('.pad,.lab-stage,.type-stage,.demo-stage');if(!stage)continue;
 stage.setAttribute('role','group');if(!stage.hasAttribute('aria-label'))stage.setAttribute('aria-label',`${entry.name}现场演示`);
 const note=document.createElement('span');note.className='sr-only';note.id=`help-${entry.key}`;note.textContent=instructions[entry.key];stage.append(note);stage.setAttribute('aria-describedby',note.id);
}
// Spoken names keep the visible label, followed by any extra instruction.
for(const el of document.querySelectorAll('button[aria-label],a[aria-label]')){const visible=el.textContent.trim().replace(/\s+/g,' '),name=el.getAttribute('aria-label');if(visible&&!name.toLowerCase().includes(visible.toLowerCase()))el.setAttribute('aria-label',`${visible}，${name}`);}
document.querySelectorAll('.split-lines,.scramble-lines').forEach(el=>el.setAttribute('role','img'));
document.querySelectorAll('.bezier-handle').forEach(el=>{el.setAttribute('aria-valuemin','0');el.setAttribute('aria-valuemax','1');el.setAttribute('aria-valuenow',el.dataset.handle==='0'?'0.22':'0.36');});
