// Export only the selected effect family. All code and artwork stay inside the HTML.
import {exhibitByKey} from './catalog.js';
import {snapshot,comparisonState} from './compare.js';
import {motion,phrase} from './core.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function buttonDemo({stage,key,p,animate,later}){
 const b=document.createElement('button');b.className='object';b.textContent={hold:'按住不放',submit:'提交',shake:'删除存档',toggle:'OFF'}[key]||key.toUpperCase();stage.append(b);
 let on=false,holding=false,charge=0;
 if(key==='wipe'){b.style.background='#f2f0eb';const fill=document.createElement('i');fill.className='wipe-fill';b.prepend(fill);const label=document.createElement('span');label.textContent='WIPE';label.style.position='relative';b.lastChild.replaceWith(label);}
 if(key==='roll'){b.textContent='';[...'ROLL OVER'].forEach((c,i)=>{const mask=document.createElement('span'),letter=document.createElement('span');mask.style.cssText='display:inline-block;overflow:hidden;height:1.3em';letter.style.cssText='display:block;white-space:pre';letter.textContent=c+'\n'+c;letter.dataset.i=i;mask.append(letter);b.append(mask);});}
 const act=()=>{
  if(key==='push')animate(b,[{transform:'translateY(10px)',boxShadow:'0 0 #111'},{transform:'translateY(0)',boxShadow:'0 10px #111'}],140);
  if(key==='ripple'){const s=document.createElement('i');Object.assign(s.style,{position:'absolute',inset:'-60%',borderRadius:'50%',background:'#fff7',pointerEvents:'none'});b.append(s);animate(s,[{transform:'scale(0)',opacity:1},{transform:'scale(1)',opacity:0}],700).onfinish=()=>s.remove();}
  if(['wipe','roll','glitch'].includes(key)){on=!on;if(key==='wipe')animate(b.querySelector('.wipe-fill'),[{transform:`scaleX(${on?0:1}) skewX(-20deg)`},{transform:`scaleX(${on?1:0}) skewX(-20deg)`}],420);if(key==='roll')b.querySelectorAll('[data-i]').forEach((ch,i)=>animate(ch,[{transform:`translateY(${on?0:-50}%)`},{transform:`translateY(${on?-50:0}%)`}],380,{delay:i*22}));if(key==='glitch')animate(b,[{textShadow:'5px 0 #fff,-5px 0 #ff5b00',transform:'translateX(5px)'},{textShadow:'-5px 0 #fff,5px 0 #111',transform:'translateX(-5px)'},{textShadow:'none',transform:'none'}],380);}
  if(key==='jelly')animate(b,[1,1.28,.82,1.1,.95,1].map((x,i)=>({transform:`scale(${x},${[1,.72,1.2,.91,1.05,1][i]})`})),750);
  if(key==='shake')animate(b,[0,-14,12,-9,6,-3,0].map(x=>({transform:`translateX(${x}px)`})),480);
  if(key==='toggle'){on=!on;b.textContent=on?'ON ●':'OFF ○';animate(b,[{transform:`translateX(${on?-33:33}px)`},{transform:`translateX(${on?38:-38}px)`},{transform:`translateX(${on?33:-33}px)`}],450);}
  if(key==='submit'&&!b.disabled){b.disabled=true;b.textContent='◌ 加载中';later(()=>{b.textContent='已提交 ✓';animate(b,[{transform:'scale(.9)'},{transform:'scale(1.06)'},{transform:'scale(1)'}],300);later(()=>{b.disabled=false;b.textContent='提交';},1600);},1400);}
  if(key==='burst')explode();
 };
 function explode(){animate(b,[{transform:'scale(1)'},{transform:'scale(.88)'}],80);later(()=>{animate(b,[{transform:'scale(.88)'},{transform:'scale(1.1)'},{transform:'scale(1)'}],450);const ring=document.createElement('i');ring.className='ring';stage.append(ring);animate(ring,[{transform:'translate(-50%,-50%) scale(.1)',opacity:1},{transform:'translate(-50%,-50%) scale(5)',opacity:0}],600).onfinish=()=>ring.remove();for(let i=0;i<36;i++){const q=document.createElement('i');q.className='spark';stage.append(q);const a=Math.random()*Math.PI*2,v=80+Math.random()*220;animate(q,[{transform:'translate(0,0)',opacity:1},{transform:`translate(${Math.cos(a)*v}px,${Math.sin(a)*v+130}px) rotate(190deg)`,opacity:0}],850).onfinish=()=>q.remove();}},125);}
 b.addEventListener('click',act);if(['wipe','roll','glitch'].includes(key))b.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')act();});
 if(key==='tilt'){stage.style.perspective='800px';const move=e=>{const r=stage.getBoundingClientRect();b.style.transform=`rotateX(${-(e.clientY-r.top-r.height/2)/r.height*28}deg) rotateY(${(e.clientX-r.left-r.width/2)/r.width*28}deg)`;};stage.addEventListener('pointermove',move);stage.addEventListener('pointerdown',move);stage.addEventListener('pointerleave',()=>b.style.transform='none');}
 if(key==='hold'){let token=0;const start=()=>{holding=true;const id=++token;let prev=performance.now();const tick=now=>{if(id!==token)return;charge=Math.max(0,Math.min(1,charge+(now-prev)*speed/1200*(holding?1:-4)));prev=now;b.style.background=`linear-gradient(90deg,#f2f0eb ${charge*100}%,#ff5b00 0)`;if(holding&&charge===1){holding=false;b.textContent='CONFIRMED ✓';explode();later(()=>{b.textContent='按住不放';charge=0;},1800);return;}if(charge>0||holding)requestAnimationFrame(tick);};requestAnimationFrame(tick);};b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);start();};b.onpointerup=b.onpointercancel=()=>holding=false;b.onkeydown=e=>{if(e.key===' '&&!e.repeat){e.preventDefault();start();}};b.onkeyup=()=>holding=false;}
}
function cursorDemo({stage,key,p,animate,later,raf}){
 const b=document.createElement('div');b.className='object';b.textContent=key==='spotlight'?'LIGHT / FIELD':'MOVE / TAP';stage.append(b);let tx=0,ty=0,x=0,y=0,last=null,index=0,points=[];
 if(key==='spotlight'){Object.assign(b.style,{width:'100%',height:'100%',background:'repeating-linear-gradient(25deg,#ff5b00 0 30px,#f2f0eb 30px 60px)',fontSize:'50px',display:'grid',placeItems:'center'});}
 if(key==='custom'){Object.assign(b.style,{borderRadius:'50%',width:'84px',height:'84px',padding:'0',mixBlendMode:'difference',color:'#111',background:'#fff',boxShadow:'none'});b.textContent='✳';stage.style.cursor='none';}
 const move=e=>{const r=stage.getBoundingClientRect();tx=e.clientX-r.left-r.width/2;ty=e.clientY-r.top-r.height/2;
  if(key==='trail'&&(!last||Math.hypot(tx-last.x,ty-last.y)>p.gap)){last={x:tx,y:ty};const q=document.createElement('i');q.className='photo';q.style.cssText=`left:calc(50% + ${tx}px);top:calc(50% + ${ty}px);width:${p.size}px;height:${p.size*.7}px;background:repeating-linear-gradient(${index++*37}deg,#111 0 10px,#ff5b00 10px 20px,#f2f0eb 20px 24px)`;stage.append(q);animate(q,[{transform:'translate(-50%,-50%) scale(.6)',opacity:0},{transform:'translate(-50%,-50%) scale(1)',opacity:1,offset:.15},{transform:'translate(-50%,-70%) scale(.9)',opacity:0}],p.life).onfinish=()=>q.remove();}
  if(key==='ink'){const q=document.createElement('i');q.className='spark';q.style.left=`calc(50% + ${tx}px)`;q.style.top=`calc(50% + ${ty}px)`;stage.append(q);points.push(q);if(points.length>36)points.shift().remove();animate(q,[{transform:'scale(2)',opacity:1},{transform:'scale(0)',opacity:0}],850).onfinish=()=>q.remove();}
 };stage.onpointermove=move;stage.onpointerdown=move;stage.onpointerleave=()=>{if(key==='magnetic')tx=ty=0;};
 raf(dt=>{const ease=1-Math.pow(1-(p.ease||.16),dt*60);x+=(tx-x)*ease;y+=(ty-y)*ease;if(key==='magnetic'){const field=Math.hypot(tx,ty)<p.radius;b.style.transform=`translate(${field?x*p.strength:0}px,${field?y*p.strength:0}px)`;}if(key==='custom')b.style.transform=`translate(${x}px,${y}px)`;if(key==='spotlight')b.style.clipPath=`circle(${p.radius}px at calc(50% + ${x}px) calc(50% + ${y}px))`;});
}
function textDemo({stage,key,p,animate,later,raf}){
 const line=document.createElement('div');line.className='word';stage.append(line);const text=p.text||({typewriter:'每个瞬间，都有名字。',scramble:'MOTION LEXICON'}[key]||'MOTION');
 const play=()=>{line.replaceChildren();if(key==='scramble'){let start=performance.now(),prev=0;const run=now=>{const elapsed=(now-start)*speed;if(elapsed-prev>=p.interval){prev=elapsed;line.textContent=[...text].map((ch,i)=>elapsed/p.duration>=i/text.length?ch:'!<>-_[]{}=+*#'.charAt(Math.random()*14)).join('');}if(elapsed<p.duration)requestAnimationFrame(run);else line.textContent=text;};requestAnimationFrame(run);return;}
 if(key==='typewriter'){let i=0;const tick=()=>{line.textContent=text.slice(0,++i)+'▌';if(i<text.length)later(tick,65);else line.textContent=text;};tick();return;}
 if(key==='mask'){line.textContent=text;animate(line,[{clipPath:'inset(100% 0 0)'},{clipPath:'inset(0 0 0)'}],1200);return;}
 [...text].forEach((c,i)=>{const span=document.createElement('span');span.textContent=c;span.style.display='inline-block';line.append(span);if(key==='split')animate(span,[{transform:'translateY(114%) rotate(7deg)',opacity:0},{transform:'translateY(0)',opacity:1}],p.duration,{delay:i*p.stagger,easing:'cubic-bezier(.16,1,.3,1)'});});};stage.onclick=play;play();
 if(key==='wave'){let t=0;raf(dt=>{t+=dt;[...line.children].forEach((c,i)=>c.style.fontWeight=500+Math.sin(t*Math.PI*2/2.2-i*.55)*400);});}
}
function timingDemo({stage,key,p,animate,raf}){
 if(key==='spring'){const b=document.createElement('button');b.className='object';b.textContent='SPRING';stage.append(b);let x=0,v=0,awake=false;const play=()=>{x=-125;v=0;awake=true;};b.onclick=play;raf(dt=>{if(!awake)return;let left=dt;while(left>0){const h=Math.min(.008,left);v+=(-p.stiffness*x-p.damping*v)*h;x+=v*h;left-=h;}b.style.transform=`translateY(${x}px)`;if(Math.abs(x)+Math.abs(v)<.1)awake=false;});play();return;}
 const n=key==='duration'?3:key==='stagger'?8:1;const row=document.createElement('div');row.className='row';stage.append(row);const items=Array.from({length:n},(_,i)=>{const el=document.createElement('button');el.className='tile';el.textContent=key==='duration'?[100,300,800][i]*p.factor+'ms':String(i+1).padStart(2,'0');row.append(el);return el;});
 let seed=p.seed||7;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const order=items.map((_,i)=>i);if(p.direction==='random')for(let i=n-1;i>0;i--){const j=Math.floor(rand()*(i+1));[order[i],order[j]]=[order[j],order[i]];}
 const play=()=>{items.forEach((el,i)=>{const rank=p.direction==='center'?Math.abs(i-(n-1)/2):p.direction==='random'?order.indexOf(i):i;animate(el,key==='stagger'?[{transform:'translateY(80px) rotate(7deg)',opacity:0},{transform:'translateY(0)',opacity:1}]:[{transform:'translateX(-70px)'},{transform:'translateX(70px)'}],key==='duration'?[100,300,800][i]*p.factor:p.duration,{delay:key==='stagger'?rank*p.gap:0,easing:key==='easing'?`cubic-bezier(${p.x1},${p.y1},${p.x2},${p.y2})`:'cubic-bezier(.16,1,.3,1)'});});};stage.onclick=play;play();
}
function gestureDemo({stage,key,p,raf,later}){
 const b=document.createElement('button');b.className='object drag';b.textContent={inertia:'DRAG / THROW',rubber:'RUBBER',swipe:'SWIPE 01',pull:'往下拉 ↓'}[key];stage.append(b);
 let x=0,y=0,vx=0,vy=0,down=false,ox=0,oy=0,last=0,sx=0,sy=0,mode='',serial=1,elapsed=0,w=0,h=0;
 new ResizeObserver(()=>{w=stage.clientWidth;h=stage.clientHeight;}).observe(stage);
 const bound=(n,limit)=>{const d=Math.max(0,Math.abs(n)-limit);return Math.sign(n)*(Math.min(Math.abs(n),limit)+(1-Math.exp(-d/100))*100*(1-p.resistance));};
 const draw=()=>b.style.transform=`translate(${x}px,${y}px) rotate(${key==='swipe'?x*.06:0}deg)`;
 b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);down=true;mode='';ox=e.clientX;oy=e.clientY;sx=x;sy=y;last=e.timeStamp;vx=vy=0;};
 b.onpointermove=e=>{if(!down)return;const dx=e.clientX-ox,dy=e.clientY-oy,dt=Math.max(.008,(e.timeStamp-last)/1000),nx=key==='pull'?0:sx+dx,ny=key==='swipe'?0:sy+dy;vx=(nx-x)/dt;vy=(ny-y)/dt;x=key==='rubber'?bound(nx,w*.25):nx;y=key==='pull'?Math.max(0,dy)*.65:key==='rubber'?bound(ny,h*.25):ny;last=e.timeStamp;draw();if(key==='pull')b.textContent=y>=p.threshold?'松手刷新 ↻':'继续下拉 ↓';};
 const release=e=>{if(!down)return;down=false;if(e.type==='pointercancel'||e.timeStamp-last>90)vx=vy=0;if(key==='swipe'){mode=Math.abs(vx)>p.threshold&&Math.abs(x)>12?'fly':'spring';vy=0;}else if(key==='pull'){mode=y>=p.threshold?'refresh':'spring';elapsed=0;if(mode==='refresh'){y=p.threshold;b.textContent='正在刷新 ◌';}}else mode=key==='inertia'?'coast':'spring';};b.onpointerup=b.onpointercancel=release;
 b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();x+=(e.key==='ArrowRight'?20:e.key==='ArrowLeft'?-20:0);y+=(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0);draw();}if(e.key==='Enter'){x=key==='pull'?0:60;y=key==='pull'?p.threshold+10:-35;vx=900;mode=key==='inertia'?'coast':key==='swipe'?'fly':key==='pull'?'refresh':'spring';elapsed=0;}};
 raf(dt=>{if(down||!mode)return;elapsed+=dt;if(mode==='refresh'){b.textContent=`刷新 ${Math.min(100,Math.round(elapsed*100000/p.duration))}%`;if(elapsed*1000>=p.duration){b.textContent='刷新完成 ✓';mode='spring';}return;}
 if(mode==='coast'){const loss=Math.exp(-p.friction/p.mass*dt);vx*=loss;vy*=loss;x+=vx*dt;y+=vy*dt;const lx=Math.max(15,w/2-85),ly=Math.max(15,h/2-65);if(Math.abs(x)>lx){x=Math.sign(x)*lx;vx*=-.36;}if(Math.abs(y)>ly){y=Math.sign(y)*ly;vy*=-.36;}if(Math.hypot(vx,vy)<2)mode='';}
 else if(mode==='fly'){x+=vx*dt;if(Math.abs(x)>w){x=y=vx=vy=0;mode='';b.textContent=`SWIPE ${String(++serial).padStart(2,'0')}`;}}
 else {let left=dt;while(left>0){const h=Math.min(left,.008),k=p.stiffness||220,c=p.damping||22,tx=key==='rubber'?Math.max(-w*.25,Math.min(w*.25,x)):0,ty=key==='rubber'?Math.max(-h*.25,Math.min(h*.25,y)):0;vx+=(k*(tx-x)-c*vx)*h;vy+=(k*(ty-y)-c*vy)*h;x+=vx*h;y+=vy*h;left-=h;}if(Math.hypot(x,y,vx,vy)<.5){x=y=vx=vy=0;mode='';}}draw();});
}
function scrollDemo({stage,key,p,animate,raf}){
 stage.classList.add('scroll-demo');const content=document.createElement('div');content.className='scroll-content';stage.append(content);const scene=document.createElement('div');scene.className='scroll-scene';content.append(scene);scene.innerHTML='<b>SCROLL<br>TO FEEL.</b><i>01 / 02 / 03</i>';let prev=0,skew=0;
 if(key==='horizontal'){scene.innerHTML='<div class="strip">'+['FIRST','SECOND','THIRD','FOURTH'].map(t=>`<b>${t}</b>`).join('')+'</div>';}
 if(key==='parallax'){scene.innerHTML='<div class="layers"><i>✳</i><b>CITY</b><strong>FIELD / 23</strong></div>';}
 stage.onscroll=()=>{const progress=stage.scrollTop/(content.offsetHeight-stage.clientHeight),delta=stage.scrollTop-prev;prev=stage.scrollTop;
 if(key==='pinned'){scene.firstChild.textContent=['FIRST FRAME','SECOND FRAME','THIRD FRAME'][Math.min(2,Math.floor(progress*3))];}
 if(key==='horizontal')scene.firstChild.style.transform=`translateX(${-progress*75}%)`;
 if(key==='reveal')scene.style.clipPath=`inset(${(1-progress)*100}% 0 0)`;
 if(key==='parallax')[...scene.firstChild.children].forEach((el,i)=>el.style.transform=`translateY(${-stage.scrollTop*[.15,.45,.9][i]}px)`);
 if(key==='velocity')skew=Math.max(-14,Math.min(14,delta*.45));};
 raf(dt=>{if(key==='velocity'){skew*=Math.pow(.88,dt*60);scene.style.transform=`skewY(${skew}deg)`;}});
}
function transitionDemo({stage,key,p,animate,later}){
 const grid=document.createElement('div');grid.className='row';stage.append(grid);let on=false;const items=Array.from({length:key==='flip'?4:1},(_,i)=>{const el=document.createElement('button');el.className='tile';el.textContent=['FIELD','SIGNAL','FORM','MOTION'][i];grid.append(el);return el;});
 const update=()=>{on=!on;items[0].textContent=on?'NEXT FRAME':'FIELD';stage.style.background=on?'#ff5b00':'#111110';};
 stage.onclick=()=>{
 if(key==='flip'){const before=items.map(el=>el.getBoundingClientRect());grid.append(grid.firstChild);items.forEach((el,i)=>{const after=el.getBoundingClientRect();animate(el,[{transform:`translate(${before[i].left-after.left}px,${before[i].top-after.top}px)`},{transform:'none'}],650,{easing:'cubic-bezier(.22,1,.36,1)'});});}
 if(key==='shared'){const el=items[0],first=el.getBoundingClientRect();on=!on;el.style.width=on?'280px':'130px';el.style.height=on?'240px':'110px';const last=el.getBoundingClientRect();animate(el,[{transformOrigin:'0 0',transform:`translate(${first.left-last.left}px,${first.top-last.top}px) scale(${first.width/last.width},${first.height/last.height})`},{transformOrigin:'0 0',transform:'none'}],750,{easing:'cubic-bezier(.22,1,.36,1)'});}
 if(key==='native'){if(document.startViewTransition)document.startViewTransition(update);else{animate(grid,[{opacity:1},{opacity:0}],325).onfinish=()=>{update();animate(grid,[{opacity:0},{opacity:1}],325);};}}
 if(key==='curtain'){for(let i=0;i<3;i++){const q=document.createElement('i');q.className='curtain';q.style.background=['#ff5b00','#f2f0eb','#111'][i];stage.append(q);animate(q,[{transform:'translateX(-125%) skewX(-12deg)'},{transform:'translateX(0) skewX(-12deg)',offset:.45},{transform:'translateX(0) skewX(-12deg)',offset:.55},{transform:'translateX(125%) skewX(-12deg)'}],920,{delay:i*65}).onfinish=()=>q.remove();}later(update,525);}
 };}
function shaderDemo({stage,key,p,raf}){
 const canvas=document.createElement('canvas');stage.append(canvas);canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%';let w=1,h=1,time=0,px=.5,py=.5,energy=0,mix=0,target=0,dir=1;
 if(key==='particles'){const ctx=canvas.getContext('2d'),mask=document.createElement('canvas');mask.width=500;mask.height=300;const c=mask.getContext('2d');c.fillStyle='#fff';c.font='900 110px sans-serif';c.textAlign='center';c.fillText('FORM',250,180);const bits=c.getImageData(0,0,500,300).data,points=[];for(let y=30;y<250;y+=7)for(let x=15;x<485;x+=7)if(bits[(y*500+x)*4+3])points.push({tx:x/500,ty:y/300,x:Math.random()*500,y:Math.random()*300,vx:0,vy:0});new ResizeObserver(()=>{w=canvas.width=stage.clientWidth;h=canvas.height=stage.clientHeight;}).observe(stage);stage.onpointermove=stage.onpointerdown=e=>{const r=stage.getBoundingClientRect();px=e.clientX-r.left;py=e.clientY-r.top;};stage.onpointerleave=()=>px=-1000;stage.onclick=()=>points.forEach(q=>{q.vx+=(Math.random()-.5)*500;q.vy+=(Math.random()-.5)*500;});raf(dt=>{ctx.fillStyle='#111';ctx.fillRect(0,0,w,h);ctx.fillStyle='#ff5b00';points.forEach(q=>{let ax=(q.tx*w-q.x)*22,ay=(q.ty*h-q.y)*22;const dx=q.x-px,dy=q.y-py,d=Math.hypot(dx,dy);if(d<85){ax+=dx/Math.max(1,d)*(1-d/85)*1900;ay+=dy/Math.max(1,d)*(1-d/85)*1900;}const drag=Math.exp(-dt*8);q.vx=(q.vx+ax*dt)*drag;q.vy=(q.vy+ay*dt)*drag;q.x+=q.vx*dt;q.y+=q.vy*dt;ctx.fillRect(q.x,q.y,2,2);});});return;}
 const gl=canvas.getContext('webgl',{antialias:false,alpha:false});if(!gl){stage.textContent='WebGL unavailable';return;}
 const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,'attribute vec2 a;varying vec2 uv;void main(){uv=a*.5+.5;gl_Position=vec4(a,0.,1.);}'));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,`precision mediump float;varying vec2 uv;uniform vec2 pointer;uniform float t,energy,progress,mode,dir;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+1.),f.x),f.y);}float fbm(vec2 p){return .5*noise(p)+.25*noise(p*2.03+11.7)+.125*noise(p*4.08+5.2)+.0625*noise(p*8.);}vec3 art(vec2 p,float s){float n=fbm(p*5.5+vec2(s));return mix(vec3(.067),vec3(1.,.357,0.),smoothstep(.25,.75,sin(p.x*16.+n*4.+s)*.5+.5));}void main(){vec2 p=uv;vec3 c;if(mode<.5){float d=distance(p,pointer);p+=normalize(p-pointer+vec2(.001))*sin(d*48.-t*6.)*exp(-d*6.)*energy*.045;c=art(p,0.);}else if(mode<1.5){float n=fbm(p*5.5);vec2 shift=vec2(n-.45)*.16*sin(progress*3.14159);c=mix(art(p+shift,0.),art(p-shift,4.),smoothstep(n-.12,n+.12,progress*1.24-.12));}else{float n=fbm(p*2.+vec2(t*.18*dir,fbm(p*3.-t*.1)));c=mix(vec3(.067),vec3(1.,.357,0.),smoothstep(.22,.62,n));c=mix(c,vec3(.949,.941,.922),smoothstep(.55,.76,n));}gl_FragColor=vec4(c,1.);}`));gl.linkProgram(program);gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const u=Object.fromEntries(['pointer','t','energy','progress','mode','dir'].map(n=>[n,gl.getUniformLocation(program,n)]));gl.uniform1f(u.mode,{distortion:0,dissolve:1,gradient:2}[key]);new ResizeObserver(()=>{w=canvas.width=stage.clientWidth;h=canvas.height=stage.clientHeight;gl.viewport(0,0,w,h);}).observe(stage);stage.onpointermove=stage.onpointerdown=e=>{const r=stage.getBoundingClientRect();px=(e.clientX-r.left)/r.width;py=1-(e.clientY-r.top)/r.height;energy=1;};stage.onpointerleave=()=>energy=0;stage.onclick=()=>{target=1-target;dir*=-1;energy=1;};raf(dt=>{time+=dt;energy*=Math.exp(-dt*2.8);mix+=Math.sign(target-mix)*Math.min(Math.abs(target-mix),dt/1.5);gl.uniform2f(u.pointer,px,py);gl.uniform1f(u.t,time);gl.uniform1f(u.energy,energy);gl.uniform1f(u.progress,mix);gl.uniform1f(u.dir,dir);gl.drawArrays(gl.TRIANGLES,0,6);});
}
const families={button:buttonDemo,cursor:cursorDemo,text:textDemo,timing:timingDemo,gesture:gestureDemo,scroll:scrollDemo,transition:transitionDemo,shader:shaderDemo};
const style=`*{box-sizing:border-box}body{margin:0;background:#f2f0eb;color:#111110;font:14px system-ui,sans-serif}main{max-width:760px;margin:32px auto;padding:20px}h1{font-size:24px}small{display:block;line-height:1.7;margin:16px 0}.scenes{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:16px}.stage{height:360px;position:relative;overflow:hidden;display:flex;align-items:center;justify-content:center;background:#111110;border:2px solid #111110;color:#f2f0eb;isolation:isolate}.object,.tile{position:relative;background:#ff5b00;border:2px solid #f2f0eb;color:#111;padding:24px;font:900 22px system-ui;box-shadow:0 10px #f2f0eb33;cursor:pointer;overflow:hidden}.drag{touch-action:none;user-select:none;width:150px;height:120px;font-size:18px}.wipe-fill{position:absolute;inset:-10%;background:#ff5b00;transform:scaleX(0) skewX(-20deg);transform-origin:left}.word{font-size:clamp(24px,6vw,56px);font-weight:900;text-align:center;overflow:hidden;max-width:95%;cursor:pointer}.row{display:flex;flex-wrap:wrap;align-items:center;justify-content:center;gap:10px;max-width:95%}.tile{font-size:14px;padding:14px;width:90px;height:100px}.ring{position:absolute;left:50%;top:50%;width:100px;height:100px;border:3px solid #ff5b00;border-radius:50%;pointer-events:none}.spark{position:absolute;left:50%;top:50%;width:6px;height:6px;background:#ff5b00;pointer-events:none}.photo{position:absolute;border:3px solid #f2f0eb;pointer-events:none}.curtain{position:absolute;inset:-10%;pointer-events:none}.scroll-demo{display:block;overflow:auto;overscroll-behavior:contain}.scroll-content{height:1100px}.scroll-scene{position:sticky;top:0;height:355px;display:grid;place-items:center;background:#ff5b00;color:#111}.scroll-scene>b{font-size:50px}.strip{display:flex;width:400%;height:100%;position:absolute;left:0;top:0}.strip>b{width:25%;display:grid;place-items:center;font-size:40px;border-right:2px solid #111}.layers{display:grid;place-items:center}.layers>*{position:absolute;font-size:80px}.layers>i{left:15%;color:#f2f0eb}.layers>strong{font-size:25px;bottom:30px}button:focus-visible{outline:3px solid #fff;outline-offset:5px}::view-transition-old(root),::view-transition-new(root){animation-duration:650ms}@media(prefers-reduced-motion:reduce){*{animation-duration:1ms!important;transition-duration:1ms!important}}`;
export function createSnippet(key){
 const entry=exhibitByKey.get(key);if(!entry)throw Error('展品不存在');const p=snapshot(key),ab=comparisonState(key),sets=ab?[ab.A,ab.B]:[p],speed=motion.speed,description=phrase(key);const source=families[entry.hall].toString();
 // Script-safe JSON protects edited text containing HTML closing tags.
 const json=value=>JSON.stringify(value).replace(/</g,'\\u003c');
 return `<!doctype html>\n<html lang="zh-CN">\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>${escape(entry.name)}</title>\n<style>${style}</style>\n<main><h1>${escape(entry.name)} / ${escape(entry.en)}</h1><small>${escape(description)}</small><div class="scenes">${sets.map((_,i)=>`<section><b>${ab?i?'B / 当前':'A / 保存':'点按、拖动或滚动以体验'}</b><div class="stage" tabindex="0" aria-label="${escape(entry.name)}"></div></section>`).join('')}</div></main>\n<script>\nconst key=${json(key)}, speed=${speed}, params=${json(sets)};\nconst demo=${source};\ndocument.querySelectorAll('.stage').forEach((stage,i)=>{\n const p=params[i],reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;\n const animate=(el,frames,duration,options={})=>el.animate(frames,{duration:reduced?1:duration/speed,fill:'forwards',...options,delay:(options.delay||0)/speed});\n const later=(fn,ms)=>setTimeout(fn,ms/speed);\n const raf=fn=>{let prev=performance.now();const draw=now=>{const dt=Math.min(.04,(now-prev)/1000)*speed;prev=now;if(!document.hidden)fn(dt);requestAnimationFrame(draw);};requestAnimationFrame(draw);};\n demo({stage,key,p,animate,later,raf});\n});\n<\/script>\n</html>`;
}
