// Run every exported file in isolation, then send trusted mouse input into its iframe.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {browser,sleep} from './cdp.mjs';
const b=await browser(19461),results=[];try{
 await b.viewport(1440,900);await b.open();const exports=await b.evaluate(`(async()=>{const {catalog}=await import('./c3/catalog.js'),{loadModule}=await import('./c3/lazy.js'),{createSnippet}=await import('./c3/snippets.js');for(const m of new Set(catalog.map(e=>e.module)))await loadModule(m);return catalog.map(e=>[e.key,createSnippet(e.key)]);})()`);
 for(const [key,html] of exports){assert.ok(!/\b(?:import|fetch)\s*\(/.test(html));await b.evaluate(`new Promise(resolve=>{document.querySelector('#isolated-code')?.remove();const f=document.createElement('iframe');f.id='isolated-code';f.style.cssText='position:fixed;left:350px;top:100px;width:650px;height:700px;border:0;z-index:300';f.srcdoc=${JSON.stringify(html)};f.onload=()=>{window.codeFrame=f;resolve(true);};document.body.append(f);})`);await sleep(100);const point=await b.evaluate(`(()=>{const d=codeFrame.contentDocument,el=d.querySelector('.object,.tile,.word,.scroll-scene,canvas')||d.querySelector('.stage'),r=el.getBoundingClientRect(),f=codeFrame.getBoundingClientRect();return {x:f.left+r.left+r.width/2,y:f.top+r.top+r.height/2};})()`);
  await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:point.x,y:point.y});await b.call('Input.dispatchMouseEvent',{type:'mousePressed',x:point.x,y:point.y,button:'left',buttons:1,clickCount:1});await sleep(key==='hold'?1250:30);if(['inertia','rubber','swipe','pull'].includes(key)){await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:point.x+80,y:point.y+(key==='pull'?150:-25),button:'left',buttons:1});}
  await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',x:point.x+(key==='pull'?0:['inertia','rubber','swipe'].includes(key)?80:0),y:point.y+(key==='pull'?150:['inertia','rubber','swipe'].includes(key)?-25:0),button:'left',clickCount:1});
  await b.evaluate(`(()=>{const s=codeFrame.contentDocument.querySelector('.stage');s.scrollTop=220;})()`);await sleep(100);assert.deepEqual(b.errors,[],key);results.push({key,bytes:Buffer.byteLength(html),passed:true});
 }
 await b.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 for(const key of ['wave','spring','typewriter','particles']){const html=exports.find(e=>e[0]===key)[1];await b.evaluate(`new Promise(resolve=>{codeFrame.remove();const f=document.createElement('iframe');f.id='isolated-code';f.style.cssText='position:fixed;left:350px;top:100px;width:650px;height:700px;z-index:300';f.srcdoc=${JSON.stringify(html)};f.onload=()=>{window.codeFrame=f;resolve(true)};document.body.append(f);})`);await sleep(140);const value=await b.evaluate(`(()=>{const d=codeFrame.contentDocument;return {key:'${key}',weight:d.querySelector('.word span')?.style.fontWeight,transform:d.querySelector('.object')?.style.transform,text:d.querySelector('.word')?.textContent,canvas:!!d.querySelector('canvas')};})()`);if(key==='wave')assert.equal(value.weight,'900');if(key==='spring')assert.equal(value.transform,'none');if(key==='typewriter')assert.equal(value.text,'每个瞬间，都有名字。');if(key==='particles')assert.equal(value.canvas,true);}
 await b.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
 const special=await b.evaluate(`(async()=>{const {restoreComparison}=await import('./c3/compare.js'),{createSnippet}=await import('./c3/snippets.js'),{shareURL}=await import('./c3/share.js'),{setSpeed}=await import('./c3/core.js');setSpeed(.75,true);await restoreComparison('spring',{A:{stiffness:180,damping:18},B:{stiffness:250,damping:7}});const code=createSnippet('spring');return {url:shareURL('spring'),abScenes:new DOMParser().parseFromString(code,'text/html').querySelectorAll('.stage').length};})()`);assert.equal(special.abScenes,2);await b.call('Page.navigate',{url:special.url});await sleep(2100);const restored=await b.evaluate(`import('./c3/compare.js').then(m=>m.comparisonState('spring'))`);assert.deepEqual(restored,{A:{stiffness:180,damping:18},B:{stiffness:250,damping:7}});assert.equal(await b.evaluate(`document.querySelector('#hudSpd').textContent`),'0.75x');assert.deepEqual(b.errors,[]);
 fs.writeFileSync(process.env.QA_OUT||'docs/review/phase4/code-checks.json',JSON.stringify({date:new Date().toISOString(),standaloneCount:results.length,results,abExport:true,abShareReload:true,reducedExports:4,errors:b.errors},null,2));console.log('43 standalone files executed with trusted input; A/B export and actual URL reload passed.');
}finally{b.close();}
