// Interaction regression checks via the local Chrome; no site build step.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {browser,sleep} from './cdp.mjs';
const b=await browser(19458),results=[];
async function check(name,expression,test){const value=await b.evaluate(expression);test(value);results.push({name,passed:true});console.log('PASS',name);}
try{
 await b.viewport(1440);await b.open();
 await check('Catalog: 43 exhibits, unique numbers and existing cards',`(async()=>{const {catalog}=await import('./c3/catalog.js');return {count:catalog.length,numbers:new Set(catalog.map(e=>e.no)).size,cards:catalog.filter(e=>document.querySelector('[data-k="'+e.key+'"]')).length};})()`,v=>assert.deepEqual(v,{count:43,numbers:43,cards:43}));
 await check('Every copied phrase can be read back, including unloaded halls',`(async()=>{const {catalog}=await import('./c3/catalog.js'),{loadModule}=await import('./c3/lazy.js'),core=await import('./c3/core.js'),{restorePhrase}=await import('./c3/phrase.js');let count=0;for(const e of catalog){await loadModule(e.module);const p=core.phrase(e.key);try{const r=await restorePhrase(p);if(r.entry.key!==e.key)throw Error('wrong target');count++;}catch(err){return {count,failed:e.key,error:err.message,phrase:p};}}return {count};})()`,v=>assert.deepEqual(v,{count:43}));
 await check('Restore speed and magnetic strength/radius/ease',`(async()=>{const p=await import('./c3/phrase.js');await p.restorePhrase('磁吸 Magnetic｜速度 0.50x｜强度 0.70 · 范围 200px · 跟手速度 0.20');const root=document.querySelector('[data-k=magnetic]');return {speed:document.querySelector('#hudSpd').textContent,values:[...root.querySelectorAll('[data-param]')].map(i=>i.value)};})()`,v=>assert.deepEqual(v,{speed:'0.50x',values:['0.7','200','0.2']}));
 await check('Custom text survives separators and is restored with timing',`(async()=>{await (await import('./c3/phrase.js')).restorePhrase('逐字错落 Split Text Stagger｜速度 0.75x｜文字「每个·瞬间｜都有名字」 · 逐字间隔 110ms · 升起时长 750ms');return {text:document.querySelector('#split-input').value,values:[...document.querySelectorAll('[data-k=split] [data-param]')].map(i=>i.value)};})()`,v=>assert.deepEqual(v,{text:'每个·瞬间｜都有名字',values:['110','750']}));
 await check('Copied custom text escapes quotes and round-trips exactly',`(async()=>{const core=await import('./c3/core.js'),{restorePhrase}=await import('./c3/phrase.js');const input=document.querySelector('#split-input'),text='名字「和」未闭「';input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));const copied=core.phrase('split');input.value='改过';input.dispatchEvent(new Event('input',{bubbles:true}));await restorePhrase(copied);return input.value;})()`,v=>assert.equal(v,'名字「和」未闭「'));
 await check('Restore all four bezier control coordinates',`(async()=>{await (await import('./c3/phrase.js')).restorePhrase('缓动曲线 Easing｜速度 1.25x｜曲线 cubic-bezier(0.34,1.35,0.64,1.00) · 时长 1200ms');return [...document.querySelectorAll('[data-k=easing] [data-param]')].map(i=>i.value);})()`,v=>assert.deepEqual(v,['0.34','1.35','0.64','1.00','1200']));
 await check('Restore spring, duration ratio and reproducible stagger seed',`(async()=>{const {restorePhrase}=await import('./c3/phrase.js'),{phrase}=await import('./c3/core.js');await restorePhrase('弹簧物理 Spring｜速度 0.80x｜刚度 420 · 阻尼 35 · 质量 1');const spring=phrase('spring');await restorePhrase('时长 Duration｜速度 1.00x｜对比 150ms / 450ms / 1200ms · 曲线 ease-out');const duration=phrase('duration');await restorePhrase('错落节奏 Stagger｜速度 1.00x｜间隔 120ms · 单张 650ms · 方向 随机 · 种子 42');const sequence=[...document.querySelectorAll('.stagger-item .mono')].map(i=>i.textContent).join(',');await restorePhrase('错落节奏 Stagger｜速度 1.00x｜间隔 120ms · 单张 650ms · 方向 随机 · 种子 42');return {spring,duration,seed:document.querySelector('[data-param=seed]').value,same:sequence===[...document.querySelectorAll('.stagger-item .mono')].map(i=>i.textContent).join(',')};})()`,v=>{assert.match(v.spring,/0.80x.*420.*35/);assert.match(v.duration,/150ms \/ 450ms \/ 1200ms/);assert.equal(v.seed,'42');assert.equal(v.same,true);});
 await check('Invalid parameter is atomic: controls and speed remain unchanged',`(async()=>{const core=await import('./c3/core.js'),{restorePhrase}=await import('./c3/phrase.js');const before=core.phrase('magnetic');let error='';try{await restorePhrase('磁吸 Magnetic｜速度 2.00x｜强度 0.20 · 范围 999px');}catch(e){error=e.message;}return {same:before===core.phrase('magnetic'),error};})()`,v=>{assert.equal(v.same,true);assert.match(v.error,/范围/);});
 await check('Bad names, duplicates, unsupported values and unknown parameters fail',`(async()=>{const {restorePhrase}=await import('./c3/phrase.js');const bad=['不存在 Effect｜速度 1.00x','磁吸 Magnetic｜速度 3.00x','磁吸 Magnetic｜速度 1.00x｜强度 0.20 · 强度 0.70','缓动曲线 Easing｜速度 1.00x｜曲线 cubic-bezier(2,1,.5,1)','涟漪 Ripple｜速度 1.00x｜扩散 999ms','弹簧物理 Spring｜速度 1.00x｜未知 1'];let count=0;for(const p of bad){try{await restorePhrase(p);}catch{count++;}}return count;})()`,v=>assert.equal(v,6));
 await check('Keyboard curve edit updates the copy phrase',`(async()=>{const {navigateExhibit}=await import('./c3/phrase.js');await navigateExhibit('easing');const handle=document.querySelector('.bezier-handle');handle.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));return (await import('./c3/core.js')).phrase('easing');})()`,v=>assert.match(v,/cubic-bezier\(0.33,1.35,0.64,1.00\)/));
 await check('All 43 exhibits carry 1–3 valid feeling labels',`(async()=>{const {catalog,feelings}=await import('./c3/catalog.js');return catalog.every(e=>e.tags.length>=1&&e.tags.length<=3&&e.tags.every(t=>feelings.includes(t))&&document.querySelector('[data-k="'+e.key+'"] .exhibit-feelings').children.length===e.tags.length);})()`,v=>assert.equal(v,true));
 await check('Feeling filters intersect: Elastic + heavy includes spring and rubber',`(()=>{document.querySelector('[data-feeling="弹"]').click();document.querySelector('[data-feeling="有重量"]').click();return [...document.querySelectorAll('.feeling-result')].map(e=>e.dataset.exhibit);})()`,v=>assert.deepEqual(v,['spring','rubber']));
 await check('Empty feeling intersection is explained and can be cleared',`(()=>{document.querySelector('[data-feeling="安静"]').click();const empty=!document.querySelector('.feeling-empty').hidden;document.querySelector('#feeling-clear').click();return {empty,all:document.querySelector('[data-feeling="全部"]').getAttribute('aria-pressed'),halls:new Set([...document.querySelectorAll('.feeling-result-top')].map(e=>e.textContent.split('/')[1].trim())).size};})()`,v=>assert.deepEqual(v,{empty:true,all:'true',halls:8}));
 await check('Feeling directory can show all 43 exhibits',`(()=>{document.querySelector('.feeling-more').click();const count=document.querySelectorAll('.feeling-result').length;document.querySelector('.feeling-more').click();return count;})()`,v=>assert.equal(v,43));
 await b.evaluate(`document.querySelector('[data-feeling="弹"]').click();document.querySelector('[data-feeling="有重量"]').click();document.querySelector('.feeling-result').click()`);await sleep(700);
 await check('Feeling result opens the right demonstration',`document.querySelector('#dTtl').textContent`,v=>assert.match(v,/37.*弹簧物理/));
 await check('Exhibit label links back to the selected feeling',`(()=>{document.querySelector('[data-k=spring] .exhibit-feelings button').click();return document.querySelector('[data-feeling="弹"]').getAttribute('aria-pressed');})()`,v=>assert.equal(v,'true'));
 await b.evaluate(`(async()=>{await (await import('./c3/phrase.js')).navigateExhibit('easing');})()`);await sleep(650);
 const drag=await b.evaluate(`(()=>{const r=document.querySelector('.bezier-handle').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2,before:Number(document.querySelector('[data-param=x1]').value)};})()`);
 await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:drag.x,y:drag.y});await b.call('Input.dispatchMouseEvent',{type:'mousePressed',x:drag.x,y:drag.y,button:'left',buttons:1,clickCount:1});await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:drag.x+20,y:drag.y-10,button:'left',buttons:1});await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',x:drag.x+20,y:drag.y-10,button:'left',clickCount:1});
 await check('Actual mouse drag changes the bezier control point',`Number(document.querySelector('[data-param=x1]').value)`,v=>assert.ok(v>drag.before+.05));
 for(const width of [390,768,1024,1440]){await b.viewport(width,width===390?844:900);await b.evaluate(`document.querySelector('#collection').scrollIntoView({behavior:'instant'})`);await sleep(200);await check(`No horizontal overflow at ${width}px`,`document.documentElement.scrollWidth<=innerWidth`,v=>assert.equal(v,true));}
 await b.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 await check('Reduced motion settles timing immediately',`(async()=>{const p=await import('./c3/phrase.js');await p.restorePhrase('错落节奏 Stagger｜速度 1.00x｜间隔 75ms · 单张 500ms · 方向 从中间 · 种子 7');return [...document.querySelectorAll('.stagger-item')].every(e=>e.style.opacity==='1');})()`,v=>assert.equal(v,true));
 await b.evaluate(`(async()=>{await (await import('./c3/phrase.js')).navigateExhibit('submit',{replay:true});})()`);await sleep(800);
 await check('Reduced-motion submit returns to an enabled button',`document.querySelector('.submit-object').disabled`,v=>assert.equal(v,false));
 await b.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await b.viewport(1440,900,false,3);
 const instrument=await b.call('Page.addScriptToEvaluateOnNewDocument',{source:`window.gpuDraws={};const draw=WebGLRenderingContext.prototype.drawArrays;WebGLRenderingContext.prototype.drawArrays=function(...args){const k=this.canvas.closest('[data-k]')?.dataset.k;if(k)window.gpuDraws[k]=(window.gpuDraws[k]||0)+1;return draw.apply(this,args);};`});
 await b.open();await b.evaluate(`document.querySelector('#hall-shader').scrollIntoView({behavior:'instant'})`);await sleep(1000);await b.evaluate(`document.querySelector('[data-k=distortion]').scrollIntoView({behavior:'instant',block:'center'})`);await sleep(500);
 await check('DPR 3: WebGL canvases are capped at 1.5x and render',`({ratios:[...document.querySelectorAll('.shader-ready canvas')].map(c=>c.width/c.clientWidth),draws:Object.values(window.gpuDraws).reduce((a,b)=>a+b,0)})`,v=>{assert.ok(v.ratios.length>=2);assert.ok(v.ratios.every(r=>r<=1.502));assert.ok(v.draws>0);});
 await b.evaluate(`document.querySelector('#collection').scrollIntoView({behavior:'instant'});document.querySelector('#dX').click()`);await sleep(600);const paused=await b.evaluate('JSON.stringify(window.gpuDraws)');await sleep(400);
 await check('Leaving Shader stops all WebGL drawing',`JSON.stringify(window.gpuDraws)`,v=>assert.equal(v,paused));
 await b.call('Page.removeScriptToEvaluateOnNewDocument',{identifier:instrument.identifier});
 const unsupported=await b.call('Page.addScriptToEvaluateOnNewDocument',{source:`const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'?null:original.call(this,type,...args);};`});await b.open();await b.evaluate(`document.querySelector('#hall-shader').scrollIntoView({behavior:'instant'});document.querySelector('[data-k=distortion]').scrollIntoView({behavior:'instant'})`);await sleep(1200);
 await check('WebGL-unavailable fallback is explicit and stays playable',`document.querySelector('[data-k=distortion] .shader-hint').textContent`,v=>assert.match(v,/不支持 WebGL/));await b.call('Page.removeScriptToEvaluateOnNewDocument',{identifier:unsupported.identifier});
 await b.viewport(390,844,true,3);await b.open();await b.evaluate(`document.querySelector('#hall-shader').scrollIntoView({behavior:'instant'})`);await sleep(900);
 for(const key of ['distortion','dissolve','gradient','particles']){await b.evaluate(`import('./c3/phrase.js').then(m=>m.navigateExhibit('${key}'))`);await sleep(900);await check(`Phone ${key}: live GPU at DPR 1`, `(()=>{const root=document.querySelector('[data-k=${key}]'),c=root.querySelector('canvas');return {ready:root.classList.contains('shader-ready'),quality:root.dataset.quality,ratio:c.width/c.clientWidth};})()`,v=>{assert.equal(v.ready,true);assert.equal(v.quality,'mobile-dpr1');assert.ok(v.ratio<=1.002);});}
 await check('All thirteen adjustable exhibits retain A/B parameters through phrases',`(async()=>{const {catalog}=await import('./c3/catalog.js'),{loadModule}=await import('./c3/lazy.js'),{snapshot,restoreComparison,comparisonState}=await import('./c3/compare.js'),{restorePhrase}=await import('./c3/phrase.js'),{phrase}=await import('./c3/core.js');let count=0;for(const e of catalog){await loadModule(e.module);const root=document.querySelector('[data-k="'+e.key+'"]');if(!root.querySelector('[data-param]'))continue;const A=snapshot(e.key),B={...A},input=root.querySelector('[data-param]');const min=Number(input.min),step=Number(input.step);B[input.dataset.param]=Number(input.value)===min?min+step:min;await restoreComparison(e.key,{A,B});const saved=phrase(e.key);await restorePhrase(saved);if(JSON.stringify(comparisonState(e.key))!==JSON.stringify({A,B}))return {failed:e.key};count++;}return {count};})()`,v=>assert.deepEqual(v,{count:13}));
 for(const [key,A,B] of [['rubber',{resistance:.2,stiffness:240},{resistance:.8,stiffness:240}],['swipe',{threshold:650,damping:18},{threshold:1400,damping:18}],['pull',{threshold:50,duration:1000},{threshold:130,duration:1000}]]){await check(`Gesture A/B ${key}: identical demo input reveals different parameters`,`(async()=>{const {navigateExhibit}=await import('./c3/phrase.js'),{restoreComparison,playComparison}=await import('./c3/compare.js');await navigateExhibit('${key}');await new Promise(r=>setTimeout(r,800));await restoreComparison('${key}',${JSON.stringify({A,B})});document.querySelector('[data-k=${key}] .ab-panel').scrollIntoView({behavior:'instant',block:'center'});await new Promise(r=>setTimeout(r,300));playComparison('${key}');return [...document.querySelectorAll('[data-k=${key}] .ab-replica')].map(root=>({transform:root.querySelector('.gesture-object').style.transform,phase:root.querySelector('.demo-stage').dataset.phase}));})()`,v=>{assert.equal(v.length,2);assert.notEqual(key==='rubber'?v[0].transform:v[0].phase,key==='rubber'?v[1].transform:v[1].phase);});}
 await check('Quoted A/B markers and unpaired literal quotes survive comparison round-trip',`(async()=>{const {snapshot,restoreComparison,comparisonState}=await import('./c3/compare.js'),{restorePhrase}=await import('./c3/phrase.js'),{phrase}=await import('./c3/core.js'),input=document.querySelector('#split-input');input.value='对比｜A/B {x}「」';input.dispatchEvent(new Event('input',{bubbles:true}));const A=snapshot('split');input.value='快｜A/B {y}「未闭';input.dispatchEvent(new Event('input',{bubbles:true}));const B=snapshot('split');await restoreComparison('split',{A,B});const p=phrase('split');await restorePhrase(p);return {same:p===phrase('split'),state:comparisonState('split'),text:input.value};})()`,v=>{assert.equal(v.same,true);assert.equal(v.state.A.text,'对比｜A/B {x}「」');assert.equal(v.state.B.text,'快｜A/B {y}「未闭');assert.equal(v.text,'快｜A/B {y}「未闭');});
 await check('A/B invalid snapshot is atomic',`(async()=>{const {restorePhrase}=await import('./c3/phrase.js'),{phrase}=await import('./c3/core.js');const before=phrase('spring');let rejected=false;try{const split=before.lastIndexOf('｜A/B '),values=JSON.parse(before.slice(split+5));values.A.stiffness=99999;await restorePhrase(before.slice(0,split)+'｜A/B '+JSON.stringify(values));}catch{rejected=true;}return rejected&&phrase('spring')===before;})()`,v=>assert.equal(v,true));
 await check('All forty-three exports parse as standalone HTML with inline scripts',`(async()=>{const {catalog}=await import('./c3/catalog.js'),{createSnippet}=await import('./c3/snippets.js');return catalog.map(e=>{const code=createSnippet(e.key),doc=new DOMParser().parseFromString(code,'text/html');new Function(doc.querySelector('script').textContent);return !!doc.querySelector('.stage')&&!doc.querySelector('script[src],link[href],img[src]');}).every(Boolean);})()`,v=>assert.equal(v,true));
 await b.evaluate(`(async()=>{const core=await import('./c3/core.js'),f=await import('./c3/frame.js');core.setSpeed(1,true);f.pauseMotion(false);await (await import('./c3/phrase.js')).navigateExhibit('spring');})()`);await sleep(900);await b.evaluate(`import('./c3/core.js').then(m=>m.replayExhibit('spring'))`);await sleep(130);await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(true))`);
 const frozen=await b.evaluate(`document.querySelector('[data-k=spring] .spring-object').style.transform`);await sleep(220);await check('Spring physics freezes exactly while paused',`document.querySelector('[data-k=spring] .spring-object').style.transform`,v=>assert.equal(v,frozen));await b.evaluate(`import('./c3/frame.js').then(m=>m.stepMotion())`);await check('One frame advances spring while keeping playback paused',`(async()=>({transform:document.querySelector('[data-k=spring] .spring-object').style.transform,paused:(await import('./c3/frame.js')).frameState.paused}))()`,v=>{assert.notEqual(v.transform,frozen);assert.equal(v.paused,true);});
 await b.evaluate(`(async()=>{(await import('./c3/frame.js')).pauseMotion(false);await (await import('./c3/phrase.js')).navigateExhibit('burst');})()`);await sleep(900);await b.evaluate(`document.querySelector('[data-k=burst] .b').click()`);await sleep(180);await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(true))`);const canvas=await b.evaluate(`document.querySelector('.impact-canvas')?.toDataURL()`);assert.ok(canvas);await sleep(200);await check('Explosion canvas freezes at a visible phase',`document.querySelector('.impact-canvas')?.toDataURL()`,v=>assert.equal(v,canvas));await b.evaluate(`import('./c3/frame.js').then(m=>m.stepMotion())`);await check('Explosion particles move exactly one frame',`document.querySelector('.impact-canvas')?.toDataURL()`,v=>assert.notEqual(v,canvas));await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(false))`);
 await b.evaluate(`import('./c3/phrase.js').then(m=>m.navigateExhibit('jelly'))`);await sleep(900);await b.evaluate(`document.querySelector('.b-jelly').click()`);await sleep(90);await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(true))`);const animationTimes=await b.evaluate(`document.querySelector('.b-jelly').getAnimations().map(a=>a.currentTime)`);assert.ok(animationTimes.length);await sleep(180);await check('Native browser animations freeze on the same clock',`document.querySelector('.b-jelly').getAnimations().map(a=>a.currentTime)`,v=>assert.deepEqual(v,animationTimes));await b.evaluate(`import('./c3/frame.js').then(m=>m.stepMotion())`);await check('One frame advances native browser animations',`document.querySelector('.b-jelly').getAnimations().map(a=>a.currentTime)`,v=>assert.ok(v[0]>animationTimes[0]));await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(false))`);
 await b.evaluate(`import('./c3/phrase.js').then(m=>m.navigateExhibit('glitch'))`);await sleep(900);await b.evaluate(`document.querySelector('.b-glitch').classList.add('is-hover')`);await sleep(90);await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(true))`);const cssTimes=await b.evaluate(`document.querySelector('.b-glitch').getAnimations({subtree:true}).map(a=>a.currentTime)`);assert.ok(cssTimes.length>=3);await sleep(180);await check('CSS animations and pseudo elements freeze exactly',`document.querySelector('.b-glitch').getAnimations({subtree:true}).map(a=>a.currentTime)`,v=>assert.deepEqual(v,cssTimes));await b.evaluate(`import('./c3/frame.js').then(m=>m.stepMotion())`);await check('One frame advances all glitch CSS layers',`document.querySelector('.b-glitch').getAnimations({subtree:true}).map(a=>a.currentTime)`,v=>assert.ok(v.every((n,i)=>n>cssTimes[i])));await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(false))`);
 await check('CSS pause is exact across thirty playback boundary races',`(async()=>{const f=await import('./c3/frame.js'),b=document.querySelector('.b-glitch');for(let i=0;i<30;i++){f.pauseMotion(false);await new Promise(r=>setTimeout(r,13+i%4*7));f.pauseMotion(true);const times=b.getAnimations({subtree:true}).map(a=>a.currentTime);await new Promise(r=>setTimeout(r,25));if(JSON.stringify(times)!==JSON.stringify(b.getAnimations({subtree:true}).map(a=>a.currentTime)))return false;await f.stepMotion();if(!b.getAnimations({subtree:true}).every((a,j)=>a.currentTime>times[j]))return false;}f.pauseMotion(false);return true;})()`,v=>assert.equal(v,true));
 await check('Global start flash also freezes and steps with the shared clock',`(async()=>{const f=await import('./c3/frame.js'),a=document.querySelector('#flash').animate([{opacity:.8},{opacity:0}],{duration:400,fill:'forwards'});await new Promise(r=>setTimeout(r,60));f.pauseMotion(true);const t=a.currentTime;await new Promise(r=>setTimeout(r,120));const frozen=a.currentTime===t;await f.stepMotion();const stepped=a.currentTime>t;a.cancel();f.pauseMotion(false);return frozen&&stepped;})()`,v=>assert.equal(v,true));
 await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(true))`);await b.evaluate(`import('./c3/core.js').then(m=>m.say('ripple'))`);const words=await b.evaluate(`document.querySelector('#dTxt').textContent`);await sleep(160);await check('Guide typewriter also freezes while playback is paused',`document.querySelector('#dTxt').textContent`,v=>assert.equal(v,words));await b.evaluate(`import('./c3/frame.js').then(m=>m.stepMotion())`);await b.evaluate(`import('./c3/frame.js').then(m=>m.stepMotion())`);await check('Guide typewriter advances on the authored clock',`document.querySelector('#dTxt').textContent.length`,v=>assert.ok(v>words.length));await b.evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(false))`);
 assert.deepEqual(b.errors,[]);results.push({name:'No uncaught JavaScript errors',passed:true});
 fs.writeFileSync(process.env.QA_OUT||'docs/review/phase4/checks.json',JSON.stringify({date:new Date().toISOString(),results},null,2));
 console.log(`${results.length} checks passed`);
}finally{b.close();}
