// Interaction regression checks via the local Chrome; no site build step.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {browser,sleep} from './cdp.mjs';
const b=await browser(19438),results=[];
async function check(name,expression,test){const value=await b.evaluate(expression);test(value);results.push({name,passed:true});console.log('PASS',name);}
try{
 await b.viewport(1440);await b.open();
 await check('Catalog: 39 exhibits, unique numbers and existing cards',`(async()=>{const {catalog}=await import('./c3/catalog.js');return {count:catalog.length,numbers:new Set(catalog.map(e=>e.no)).size,cards:catalog.filter(e=>document.querySelector('[data-k="'+e.key+'"]')).length};})()`,v=>assert.deepEqual(v,{count:39,numbers:39,cards:39}));
 await check('Every copied phrase can be read back, including unloaded halls',`(async()=>{const {catalog}=await import('./c3/catalog.js'),{loadModule}=await import('./c3/lazy.js'),core=await import('./c3/core.js'),{restorePhrase}=await import('./c3/phrase.js');let count=0;for(const e of catalog){await loadModule(e.module);const p=core.phrase(e.key);try{const r=await restorePhrase(p);if(r.entry.key!==e.key)throw Error('wrong target');count++;}catch(err){return {count,failed:e.key,error:err.message,phrase:p};}}return {count};})()`,v=>assert.deepEqual(v,{count:39}));
 await check('Restore speed and magnetic strength/radius/ease',`(async()=>{const p=await import('./c3/phrase.js');await p.restorePhrase('磁吸 Magnetic｜速度 0.50x｜强度 0.70 · 范围 200px · 跟手速度 0.20');const root=document.querySelector('[data-k=magnetic]');return {speed:document.querySelector('#hudSpd').textContent,values:[...root.querySelectorAll('[data-param]')].map(i=>i.value)};})()`,v=>assert.deepEqual(v,{speed:'0.50x',values:['0.7','200','0.2']}));
 await check('Custom text survives separators and is restored with timing',`(async()=>{await (await import('./c3/phrase.js')).restorePhrase('逐字错落 Split Text Stagger｜速度 0.75x｜文字「每个·瞬间｜都有名字」 · 逐字间隔 110ms · 升起时长 750ms');return {text:document.querySelector('#split-input').value,values:[...document.querySelectorAll('[data-k=split] [data-param]')].map(i=>i.value)};})()`,v=>assert.deepEqual(v,{text:'每个·瞬间｜都有名字',values:['110','750']}));
 await check('Restore all four bezier control coordinates',`(async()=>{await (await import('./c3/phrase.js')).restorePhrase('缓动曲线 Easing｜速度 1.25x｜曲线 cubic-bezier(0.34,1.35,0.64,1.00) · 时长 1200ms');return [...document.querySelectorAll('[data-k=easing] [data-param]')].map(i=>i.value);})()`,v=>assert.deepEqual(v,['0.34','1.35','0.64','1.00','1200']));
 await check('Restore spring, duration ratio and reproducible stagger seed',`(async()=>{const {restorePhrase}=await import('./c3/phrase.js'),{phrase}=await import('./c3/core.js');await restorePhrase('弹簧物理 Spring｜速度 0.80x｜刚度 420 · 阻尼 35 · 质量 1');const spring=phrase('spring');await restorePhrase('时长 Duration｜速度 1.00x｜对比 150ms / 450ms / 1200ms · 曲线 ease-out');const duration=phrase('duration');await restorePhrase('错落节奏 Stagger｜速度 1.00x｜间隔 120ms · 单张 650ms · 方向 随机 · 种子 42');const sequence=[...document.querySelectorAll('.stagger-item .mono')].map(i=>i.textContent).join(',');await restorePhrase('错落节奏 Stagger｜速度 1.00x｜间隔 120ms · 单张 650ms · 方向 随机 · 种子 42');return {spring,duration,seed:document.querySelector('[data-param=seed]').value,same:sequence===[...document.querySelectorAll('.stagger-item .mono')].map(i=>i.textContent).join(',')};})()`,v=>{assert.match(v.spring,/0.80x.*420.*35/);assert.match(v.duration,/150ms \/ 450ms \/ 1200ms/);assert.equal(v.seed,'42');assert.equal(v.same,true);});
 await check('Invalid parameter is atomic: controls and speed remain unchanged',`(async()=>{const core=await import('./c3/core.js'),{restorePhrase}=await import('./c3/phrase.js');const before=core.phrase('magnetic');let error='';try{await restorePhrase('磁吸 Magnetic｜速度 2.00x｜强度 0.20 · 范围 999px');}catch(e){error=e.message;}return {same:before===core.phrase('magnetic'),error};})()`,v=>{assert.equal(v.same,true);assert.match(v.error,/范围/);});
 await check('Bad names, duplicates, unsupported values and unknown parameters fail',`(async()=>{const {restorePhrase}=await import('./c3/phrase.js');const bad=['不存在 Effect｜速度 1.00x','磁吸 Magnetic｜速度 3.00x','磁吸 Magnetic｜速度 1.00x｜强度 0.20 · 强度 0.70','缓动曲线 Easing｜速度 1.00x｜曲线 cubic-bezier(2,1,.5,1)','涟漪 Ripple｜速度 1.00x｜扩散 999ms','弹簧物理 Spring｜速度 1.00x｜未知 1'];let count=0;for(const p of bad){try{await restorePhrase(p);}catch{count++;}}return count;})()`,v=>assert.equal(v,6));
 await check('Keyboard curve edit updates the copy phrase',`(async()=>{const {navigateExhibit}=await import('./c3/phrase.js');await navigateExhibit('easing');const handle=document.querySelector('.bezier-handle');handle.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));return (await import('./c3/core.js')).phrase('easing');})()`,v=>assert.match(v,/cubic-bezier\(0.33,1.35,0.64,1.00\)/));
 await check('All 39 exhibits carry 1–3 valid feeling labels',`(async()=>{const {catalog,feelings}=await import('./c3/catalog.js');return catalog.every(e=>e.tags.length>=1&&e.tags.length<=3&&e.tags.every(t=>feelings.includes(t))&&document.querySelector('[data-k="'+e.key+'"] .exhibit-feelings').children.length===e.tags.length);})()`,v=>assert.equal(v,true));
 await check('Feeling filters intersect: elastic + heavy finds only Spring',`(()=>{document.querySelector('[data-feeling="弹"]').click();document.querySelector('[data-feeling="有重量"]').click();return [...document.querySelectorAll('.feeling-result')].map(e=>e.dataset.exhibit);})()`,v=>assert.deepEqual(v,['spring']));
 await check('Empty feeling intersection is explained and can be cleared',`(()=>{document.querySelector('[data-feeling="安静"]').click();const empty=!document.querySelector('.feeling-empty').hidden;document.querySelector('#feeling-clear').click();return {empty,all:document.querySelector('[data-feeling="全部"]').getAttribute('aria-pressed'),halls:new Set([...document.querySelectorAll('.feeling-result-top')].map(e=>e.textContent.split('/')[1].trim())).size};})()`,v=>assert.deepEqual(v,{empty:true,all:'true',halls:7}));
 await check('Feeling directory can show all 39 exhibits',`(()=>{document.querySelector('.feeling-more').click();const count=document.querySelectorAll('.feeling-result').length;document.querySelector('.feeling-more').click();return count;})()`,v=>assert.equal(v,39));
 await b.evaluate(`document.querySelector('[data-feeling="弹"]').click();document.querySelector('[data-feeling="有重量"]').click();document.querySelector('.feeling-result').click()`);await sleep(700);
 await check('Feeling result opens the right demonstration',`document.querySelector('#dTtl').textContent`,v=>assert.match(v,/37.*弹簧物理/));
 await check('Exhibit label links back to the selected feeling',`(()=>{document.querySelector('[data-k=spring] .exhibit-feelings button').click();return document.querySelector('[data-feeling="弹"]').getAttribute('aria-pressed');})()`,v=>assert.equal(v,'true'));
 for(const width of [390,768,1024,1440]){await b.viewport(width,width===390?844:900);await b.evaluate(`document.querySelector('#collection').scrollIntoView({behavior:'instant'})`);await sleep(200);await check(`No horizontal overflow at ${width}px`,`document.documentElement.scrollWidth<=innerWidth`,v=>assert.equal(v,true));}
 await b.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 await check('Reduced motion settles timing immediately',`(async()=>{const p=await import('./c3/phrase.js');await p.restorePhrase('错落节奏 Stagger｜速度 1.00x｜间隔 75ms · 单张 500ms · 方向 从中间 · 种子 7');return [...document.querySelectorAll('.stagger-item')].every(e=>e.style.opacity==='1');})()`,v=>assert.equal(v,true));
 assert.deepEqual(b.errors,[]);results.push({name:'No uncaught JavaScript errors',passed:true});
 fs.writeFileSync('docs/review/phase3/checks.json',JSON.stringify({date:new Date().toISOString(),results},null,2));
 console.log(`${results.length} checks passed`);
}finally{b.close();}
