import fs from 'node:fs';
import {browser,sleep} from './cdp.mjs';
const out='docs/review/phase4',b=await browser(19460);fs.mkdirSync(out,{recursive:true});
const evaluate=b.evaluate;
async function align(selector,top=125){await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.closest('.hall')?.style.setProperty('content-visibility','visible');el.scrollIntoView({block:'center',behavior:'instant'});})()`);await sleep(500);await evaluate(`scrollTo({top:scrollY+document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect().top-${top},behavior:'instant'})`);await sleep(150);}
async function section(selector,file){await align(selector);await evaluate(`document.querySelector('#dX').click();document.querySelector('.hud').style.visibility='hidden'`);const clip=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:0,y:r.top+scrollY,width:innerWidth,height:r.height,scale:1};})()`);await b.shot(`${out}/${file}.png`,clip);await evaluate(`document.querySelector('.hud').style.visibility=''`);}
async function navigate(key){await evaluate(`import('./c3/phrase.js').then(m=>m.navigateExhibit('${key}'))`);await sleep(900);}
try{
 await b.viewport(1440,900,false,1);await b.open();await evaluate(`import('./c3/lazy.js').then(m=>m.loadModule('gesture'))`);await section('#hall-gesture','desktop-gesture');
 await navigate('spring');await evaluate(`(async()=>{await (await import('./c3/compare.js')).restoreComparison('spring',{A:{stiffness:180,damping:18},B:{stiffness:250,damping:7}});document.querySelector('#dX').click();})()`);await align('[data-k=spring] .ab-panel',265);await evaluate(`document.querySelector('[data-k=spring] .ab-play').click();document.querySelector('#dX').click()`);await sleep(190);await b.shot(`${out}/desktop-ab.png`);
 await navigate('burst');await evaluate(`import('./c3/core.js').then(m=>m.setSpeed(.1,true))`);await evaluate(`document.querySelector('[data-k=burst] .b').click()`);await sleep(1350);await evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(true))`);await evaluate(`document.querySelector('#dTxt').click();document.querySelector('#speed-toggle').click()`);await b.shot(`${out}/slow-console.png`);await evaluate(`import('./c3/frame.js').then(m=>m.pauseMotion(false))`);
 await navigate('inertia');await evaluate(`import('./c3/phrase.js').then(m=>m.restorePhrase('惯性拖拽 Inertia Drag｜速度 0.75x｜摩擦 2.75 · 质量 2.2'))`);const url=await evaluate(`import('./c3/share.js').then(m=>m.shareURL('inertia'))`);fs.writeFileSync(`${out}/shared-example.txt`,url+'\n');await b.call('Page.navigate',{url});await sleep(2000);await evaluate(`document.fonts.ready.then(()=>true)`);await b.shot(`${out}/shared-restored.png`);
 await evaluate(`import('./c3/share.js').then(m=>m.showCode('inertia'))`);await sleep(350);await b.shot(`${out}/desktop-code.png`);await evaluate(`document.querySelector('.code-close').click()`);
 await b.viewport(390,844,true,1);await b.call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await b.open();await evaluate(`import('./c3/lazy.js').then(m=>m.loadModule('gesture'))`);await section('#hall-gesture','mobile-gesture-full');await navigate('inertia');await b.shot(`${out}/mobile-gesture.png`);
 await navigate('swipe');const r=await evaluate(`(()=>{const r=document.querySelector('[data-k=swipe] .gesture-object').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2};})()`);await b.call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x,y:r.y}]});await b.call('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+75,y:r.y-18}]});await b.shot(`${out}/mobile-swipe.png`);await b.call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await navigate('spring');await evaluate(`import('./c3/compare.js').then(m=>m.restoreComparison('spring',{A:{stiffness:180,damping:18},B:{stiffness:250,damping:7}}))`);await align('[data-k=spring] .ab-panel',230);await evaluate(`document.querySelector('[data-k=spring] .ab-play').click()`);await sleep(180);await b.shot(`${out}/mobile-ab.png`);
 await navigate('particles');await sleep(1000);await b.shot(`${out}/mobile-shader.png`);
 await b.viewport(1440,900,false,1);await b.open();await evaluate(`(async()=>{const {guidePoses}=await import('./c3/guide.js');const sheet=document.createElement('section');sheet.id='guide-sheet';sheet.style.cssText='position:absolute;left:0;top:0;width:1440px;height:650px;background:var(--paper);z-index:500;padding:48px 50px;border-bottom:10px solid var(--or)';sheet.innerHTML='<span class="mono" style="color:#a83c00;font-size:11px">FIELD GUIDE / CHARACTER STUDY / 04</span><h1 style="font:900 40px var(--heavy);margin:14px 0 32px">同一个导览员，五种表情。</h1><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:18px">'+guidePoses.map(([key,label,file],i)=>'<figure style="margin:0;border:2px solid var(--ink);background:white;box-shadow:5px 5px 0 var(--ink)"><img src="../assets/city-web/'+file+'" style="display:block;width:100%;height:325px;object-fit:contain"><figcaption style="padding:17px 15px;background:'+(i%2?'var(--or)':'var(--ink)')+';color:'+(i%2?'var(--ink)':'var(--paper)')+'"><b style="font:900 20px var(--heavy)">'+label+'</b><small class="mono" style="display:block;font-size:8px;margin-top:8px">0'+(i+1)+' / '+key.toUpperCase()+'</small></figcaption></figure>').join('')+'</div>';document.body.append(sheet);await Promise.all([...sheet.querySelectorAll('img')].map(im=>im.decode()));scrollTo(0,0);})()`);await b.shot(`${out}/guide-expressions.png`,{x:0,y:0,width:1440,height:650,scale:1});
 console.log('Review screenshots saved. Errors:',JSON.stringify(b.errors));
}finally{b.close();}
